### ISSUE TITLE
How i can ignore files and directories ?

### ISSUE THREAD

**Issue by sharazghouri** [kevinpainchaud/simple-ftp-deploy-action#2]

**Comment by kevinpainchaud** [comment]
Hello,
Thank you for your contribution.
Sorry for the response time, but I don't have much time to develop these past few days.
I'm looking to add an option to ignore certain files / folders.
I will keep you posted on my progress. ;)

**Comment by kevinpainchaud** [comment]
I finally found the time to add this option.

You can now ignore file(s) and/or directorie(s) by adding this:
`exclude: "'^logs/' '^README.md'"`
It's an array of regular expressions.

You will also need to use the latest version: **v1.1.0**

I added some documentation in the README.md: https://github.com/kevinpainchaud/simple-ftp-deploy-action#exclude

Hoping it will help you. 😉
